In [6]:
import pandas as pd
from pathlib import Path

#authors:  Acarie Jenkens, Carrie Bates, Corey Monsma, Parker Teske, Stargliy Bobby

# File to Load (use the absolute path per class exercise. Used on an Windows maching)
housing_path = Path("Resources/Affordable_Housing_import.csv")

# Read the housing file
housing_data_df = pd.read_csv(housing_path)

#to upper so we can perform a join
housing_data_df['deathcity'] = housing_data_df['deathcity'].str.upper()

#needed to rename column names for easier import into SQL database columns
housing_data_df.head()

,Year,Town Code,deathcity,2010 Census Units,Government Assisted,Tenant Rental Assistance,Single Family CHFA/ USDA Mortgages,Deed Restricted Units,Total Assisted Units,Percent Affordable
0,2020,1,ANDOVER,1317,18.0,1,32,0,51,3.87
1,2020,2,ANSONIA,8148,349.0,764,147,0,1260,15.46
2,2020,3,ASHFORD,1903,32.0,0,36,0,68,3.57
3,2020,4,AVON,7389,244.0,16,44,0,304,4.11
4,2020,5,BARKHAMSTED,1589,0.0,6,23,0,29,1.83

In [3]:


housing_data_df.to_csv("Resources/clean_housing.csv", index=False, header=True)